<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net11.0</TargetFramework>
        <LangVersion>14</LangVersion>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\Prism.Core\Prism.Core.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Semver" />
      <PackageReference Include="Tomlyn" />
    </ItemGroup>

</Project>
