<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net11.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="DotMake.CommandLine" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Prism.Build\Prism.Build.csproj" />
    </ItemGroup>

</Project>
