set(PRISM_HEADERS include/prism/core/exports.h
        include/prism/core/per_project_boilerplate.hpp
        include/prism/core/names.hpp
        include/prism/core/macros.hpp
)

set(PRISM_MODULES
        src/text/name.cpp
        src/memory/buffer_pool.cpp
        src/syntax/green/node.cpp
        src/syntax/green/token.cpp
        src/diagnostics/info.cpp
        src/syntax/trivia.cpp
        src/parser/lexer.cpp
        src/syntax/green/trivia.cpp
        src/parser/token_stream.cpp
        generated/syntax/green/types.cpp
        generated/syntax/green/declarations.cpp
        generated/syntax/green/expressions.cpp
        generated/syntax/green/clauses.cpp
        generated/syntax/green/statements.cpp
        src/syntax/green/list.cpp
        generated/syntax/clauses.cpp
        generated/syntax/declarations.cpp
        generated/syntax/expressions.cpp
        generated/syntax/statements.cpp
        generated/syntax/types.cpp
        generated/syntax/top_level.cpp
        generated/syntax/green/top_level.cpp
        src/parser/syntax_parser.cpp
        src/parser/language_parser.cpp
        src/syntax/green/child_list.cpp
        src/syntax/green/view.cpp
        generated/syntax/green/structured_trivia.cpp
        generated/syntax/structured_trivia.cpp
        generated/syntax/names.cpp
        generated/syntax/green/names.cpp
        generated/syntax/directives.cpp
        generated/syntax/green/directives.cpp
        src/syntax/node_or_token.cpp
        src/symbols/merged_namespace_symbol.cpp
        src/binder/signature_binder.cpp
        src/binder/binder_helpers.cpp
        src/symbols/namespace_symbol.cpp
        src/binder/expression_binder.cpp
        src/symbols/function_symbol.cpp
        src/semantic/conversion_classifier.cpp
        src/symbols/intrinsic.cpp
        src/text/name.ixx
        src/memory/alignment.ixx
        src/memory/arena_allocator.ixx
        src/memory/buffer_pool.ixx
        generated/syntax/kind.ixx
        src/syntax/green/node.ixx
        src/syntax/flags.ixx
        src/util/enum_class_flags.ixx
        src/util/noncopyable.ixx
        src/util/make_array.ixx
        src/memory/ref_counted_ptr.ixx
        src/type_traits/basic.ixx
        src/core.ixx
        src/diagnostics/descriptor.ixx
        src/diagnostics/severity.ixx
        src/diagnostics/info.ixx
        src/syntax/token.ixx
        src/syntax/green/token.ixx
        src/syntax/green/trivia.ixx
        src/syntax/literals.ixx
        src/util/optional.ixx
        src/util/hashing.ixx
        src/type_traits/comparison.ixx
        src/util/numerics.ixx
        src/syntax/trivia.ixx
        src/text/text_span.ixx
        src/text/source_file.ixx
        src/syntax/list_view.ixx
        src/parser/lexer.ixx
        src/text/cursor.ixx
        src/parser/token_stream.ixx
        src/syntax/node.ixx
        src/syntax/tree.ixx
        generated/syntax/green/types.ixx
        generated/syntax/green/declarations.ixx
        src/syntax/green/list.ixx
        generated/syntax/green/expressions.ixx
        generated/syntax/green/clauses.ixx
        src/syntax/green/separated_list.ixx
        generated/syntax/green/statements.ixx
        generated/syntax/lexing_utils.ixx
        src/memory/persistent_allocator.ixx
        src/syntax/lifetime.ixx
        src/util/exceptions.ixx
        src/syntax/tree.cpp
        src/syntax/node.cpp
        src/syntax/token.cpp
        src/syntax/lifetime.cpp
        src/syntax/list.ixx
        src/syntax/list.cpp
        src/syntax/child_list.ixx
        src/syntax/child_list.cpp
        src/util/overload.ixx
        src/syntax/node_or_token.ixx
        generated/syntax/clauses.ixx
        generated/syntax/declarations.ixx
        generated/syntax/expressions.ixx
        generated/syntax/statements.ixx
        generated/syntax/types.ixx
        src/parser/language_parser.ixx
        generated/syntax/top_level.ixx
        generated/syntax/green/top_level.ixx
        src/parser/syntax_parser.ixx
        generated/diagnostics/codes.ixx
        generated/diagnostics/registry.ixx
        src/diagnostics/syntax_info.ixx
        src/diagnostics/syntax_info.cpp
        generated/diagnostics/traits.ixx
        src/text/writer.ixx
        src/text/string_writer.ixx
        src/syntax/green/last_token_replacer.ixx
        src/syntax/green/first_token_replacer.ixx
        src/syntax/green/view.ixx
        src/syntax/green/child_list.ixx
        generated/syntax/green/structured_trivia.ixx
        generated/syntax/structured_trivia.ixx
        src/type_traits/visitor.ixx
        generated/syntax/green/visit.ixx
        src/util/enum_set.ixx
        src/symbols/symbol.ixx
        src/symbols/type_symbol.ixx
        src/symbols/function_symbol.ixx
        src/symbols/parameter_symbol.ixx
        src/symbols/variable_symbol.ixx
        src/util/ref.ixx
        src/symbols/kind.ixx
        src/symbols/assembly_symbol.ixx
        src/symbols/namespace_symbol.ixx
        src/symbols/named_type_symbol.ixx
        generated/syntax/green/names.ixx
        generated/syntax/names.ixx
        generated/syntax/directives.ixx
        generated/syntax/green/directives.ixx
        src/semantic/semantic_lifetime.ixx
        generated/syntax/visit.ixx
        src/symbols/source.ixx
        src/symbols/symbol.cpp
        src/symbols/visit.ixx
        src/util/lazy.ixx
        src/symbols/source.cpp
        src/semantic/compilation.ixx
        src/semantic/compilation.cpp
        src/binder/declaration_scope.ixx
        src/binder/declaration_scope.cpp
        src/diagnostics/diagnostic.ixx
        src/diagnostics/diagnostic.cpp
        src/diagnostics/location.ixx
        src/diagnostics/location.cpp
        src/diagnostics/diagnostic_bag.ixx
        src/diagnostics/diagnostic_bag.cpp
        src/semantic/semantic_model.ixx
        src/semantic/semantic_model.cpp
        src/syntax/reference.ixx
        src/binder/declaration_scope_builder.ixx
        src/binder/declaration_scope_builder.cpp
        src/binder/semantic_mappings.ixx
        src/binder/semantic_mappings.cpp
        src/symbols/merged_namespace_symbol.ixx
        src/symbols/intrinsic.ixx
        src/binder/signature_binder.ixx
        src/binder/binding_helpers.ixx
        src/symbols/error_type_symbol.ixx
        src/semantic/lookup_result.ixx
        src/semantic/bound/bound_node.ixx
        src/semantic/bound/bound_statement.ixx
        src/semantic/bound/bound_expression.ixx
        src/semantic/constant_value.ixx
        src/semantic/operations.ixx
        src/binder/expression_binder.ixx
        src/semantic/bound_node_lookup.ixx
        src/semantic/conversion.ixx
        src/semantic/bound_node_lookup.cpp
        src/symbols/assembly_symbol.cpp
        src/symbols/parameter_symbol.cpp
        src/symbols/variable_symbol.cpp
        src/symbols/named_type_symbol.cpp
        src/semantic/conversion_classifier.ixx
        src/context/target_settings.ixx
        src/symbols/lexical_sort_key.ixx
        src/symbols/lexical_sort_key.cpp
        src/memory/default_allocator.ixx
        src/collections/immutable_array.ixx
        src/collections/immutable_small_array.ixx
        src/collections/immutable_hash_map.ixx
        src/collections/immutable_hash_table.ixx
        src/collections/immutable_hash_set.ixx
        src/collections/immutable_ordered_set.ixx
        src/util/lazy_value.ixx
        src/declarations/declaration.ixx
        src/declarations/single_declaration.ixx
        src/declarations/single_namespace_declaration.ixx
        src/declarations/single_root_namespace_declaration.ixx
        src/declarations/merged_declaration.ixx
        src/declarations/merged_namespace_declaration.ixx
        src/declarations/merged_namespace_declaration.cpp
        src/declarations/declaration_table.ixx
        src/declarations/declaration_table.cpp
        src/declarations/visit.ixx
        src/declarations/declaration_tree_builder.ixx
        src/declarations/declaration_tree_builder.cpp
        src/semantic/syntax_and_declaration_manager.ixx
        src/semantic/syntax_and_declaration_manager.cpp
        src/binder/binder.ixx
        src/binder/binder.cpp
        src/binder/local_scope_binder.ixx
        src/binder/local_scope_binder.cpp
        src/binder/default_local_scope_binder.ixx
        src/binder/block_binder.ixx
        src/binder/terminal_binder.ixx
        src/binder/terminal_binder.cpp
        src/binder/block_binder.cpp
        src/binder/binder_factory.ixx
        src/binder/binder_factory.cpp
        src/binder/member_container_binder.ixx
        src/symbols/member_container_symbol.ixx
        src/binder/member_container_binder.cpp
        src/binder/lookup_context.ixx
        src/binder/lookup_context.cpp
)

add_library(prism_core ${PRISM_HEADERS} ${PRISM_MODULES})
prism_add_boilerplate(prism_core)

target_include_directories(prism_core PUBLIC include
                                      PRIVATE src/inline
                                              src)

target_link_libraries(prism_core
        PUBLIC Boost::cppm
                uni-algo::cppm
                libassert::cppm
        PRIVATE xxHash::cpp)

target_sources(prism_core PUBLIC
        FILE_SET CXX_MODULES
        FILES
        ${PRISM_MODULES})

target_compile_definitions(prism_core PRIVATE PRISM_CORE_EXPORT)

if (PRISM_BUILD_TESTS)
    add_subdirectory(tests)
endif()
